# Site settings
title: 'PostCSS Tidy Columns'
repo: https://github.com/goodguyry/postcss-tidy-columns

# Development/Serve
port: 8080

# Build settings
markdown: kramdown
highlighter: rouge
include: [_pages]
exclude: [package.json, package-lock.json]
timezone: America/Los_Angeles

# kramdown settings
kramdown:
  auto_ids: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
